[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --ignore-scripts && npm run build"

[deploy]
startCommand = "cd server && node dist/main.js"
healthcheckPath = "/api/health"
restartPolicyType = "always"